# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_PWM_Gen_Daan_wrapper_0_0/Main_block_PWM_Gen_Daan_wrapper_0_0.xci
# IP: The module: 'Main_block_PWM_Gen_Daan_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan || ORIG_REF_NAME==PWM_Gen_Daan} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmcalculator_0_0/PWM_Gen_Daan_pwmcalculator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmsimple_0_0/PWM_Gen_Daan_pwmsimple_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmsimple_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmsimple_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_ClockDivider100kHz_0_0/PWM_Gen_Daan_ClockDivider100kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan_ooc.xdc

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_PWM_Gen_Daan_wrapper_0_0/Main_block_PWM_Gen_Daan_wrapper_0_0.xci
# IP: The module: 'Main_block_PWM_Gen_Daan_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan || ORIG_REF_NAME==PWM_Gen_Daan} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmcalculator_0_0/PWM_Gen_Daan_pwmcalculator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmsimple_0_0/PWM_Gen_Daan_pwmsimple_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmsimple_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmsimple_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_ClockDivider100kHz_0_0/PWM_Gen_Daan_ClockDivider100kHz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan_ooc.xdc
