# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mgurl/Downloads/base.xdc

# Block Designs: bd/debug_module/debug_module.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module || ORIG_REF_NAME==debug_module} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_Clock_div_0_0/debug_module_Clock_div_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_Clock_div_0_0 || ORIG_REF_NAME==debug_module_Clock_div_0_0} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_echo_analyzer_0_0/debug_module_echo_analyzer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_echo_analyzer_0_0 || ORIG_REF_NAME==debug_module_echo_analyzer_0_0} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_segment_test_2_0_0/debug_module_segment_test_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_segment_test_2_0_0 || ORIG_REF_NAME==debug_module_segment_test_2_0_0} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_trigger_pulse_gen_1_0_0/debug_module_trigger_pulse_gen_1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_trigger_pulse_gen_1_0_0 || ORIG_REF_NAME==debug_module_trigger_pulse_gen_1_0_0} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_clk_wiz_0_0 || ORIG_REF_NAME==debug_module_clk_wiz_0_0} -quiet] -quiet

# IP: bd/debug_module/ip/debug_module_seg_buff_0_0/debug_module_seg_buff_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==debug_module_seg_buff_0_0 || ORIG_REF_NAME==debug_module_seg_buff_0_0} -quiet] -quiet

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/debug_module_ooc.xdc
