# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.srcs/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0.xci
# IP: The module: 'debug_module_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.srcs/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0.xci
# IP: The module: 'debug_module_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mgurl/Documents/School/Year_2/DD/Ultrasonic_sensor/project_1/project_1.gen/sources_1/bd/debug_module/ip/debug_module_clk_wiz_0_0/debug_module_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'debug_module_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
