# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_Speed_sensor_input_d_0_0/Main_block_Speed_sensor_input_d_0_0.xci
# IP: The module: 'Main_block_Speed_sensor_input_d_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec || ORIG_REF_NAME==Speed_sensor_input_dec} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_pulsecounter_0_0/Speed_sensor_input_dec_pulsecounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_ClockDivider1kHz_0_0/Speed_sensor_input_dec_ClockDivider1kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_speedcalc_0_0/Speed_sensor_input_dec_speedcalc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_speedcalc_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_speedcalc_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec_ooc.xdc

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_Speed_sensor_input_d_0_0/Main_block_Speed_sensor_input_d_0_0.xci
# IP: The module: 'Main_block_Speed_sensor_input_d_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec || ORIG_REF_NAME==Speed_sensor_input_dec} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_pulsecounter_0_0/Speed_sensor_input_dec_pulsecounter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_ClockDivider1kHz_0_0/Speed_sensor_input_dec_ClockDivider1kHz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0} -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_speedcalc_0_0/Speed_sensor_input_dec_speedcalc_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_speedcalc_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_speedcalc_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec_ooc.xdc
