# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0.xci
# IP: The module: 'Main_block_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.srcs/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0.xci
# IP: The module: 'Main_block_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Main_block_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
