# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/daanv/Documents/GitHub/MO5_MO6/base.xdc

# Block Designs: bd/Speed_sensor_input_dec/Speed_sensor_input_dec.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec || ORIG_REF_NAME==Speed_sensor_input_dec} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_pulsecounter_0_0/Speed_sensor_input_dec_pulsecounter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_ClockDivider1kHz_0_0/Speed_sensor_input_dec_ClockDivider1kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_speedcalc_0_0/Speed_sensor_input_dec_speedcalc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_speedcalc_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_speedcalc_0_0} -quiet] -quiet

# Block Designs: bd/PWM_Gen_Daan/PWM_Gen_Daan.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan || ORIG_REF_NAME==PWM_Gen_Daan} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmcalculator_0_0/PWM_Gen_Daan_pwmcalculator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmsimple_0_0/PWM_Gen_Daan_pwmsimple_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmsimple_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmsimple_0_0} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_ClockDivider100kHz_0_0/PWM_Gen_Daan_ClockDivider100kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0} -quiet] -quiet

# Block Designs: bd/seg_display_Daan/seg_display_Daan.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan || ORIG_REF_NAME==seg_display_Daan} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_bin14_to_bcd_0_0/seg_display_Daan_bin14_to_bcd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_bin14_to_bcd_0_0 || ORIG_REF_NAME==seg_display_Daan_bin14_to_bcd_0_0} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_ClockDivider4kHz_0_0/seg_display_Daan_ClockDivider4kHz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_ClockDivider4kHz_0_0 || ORIG_REF_NAME==seg_display_Daan_ClockDivider4kHz_0_0} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_SevenSegmentDriver_0_0/seg_display_Daan_SevenSegmentDriver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_SevenSegmentDriver_0_0 || ORIG_REF_NAME==seg_display_Daan_SevenSegmentDriver_0_0} -quiet] -quiet

# Block Designs: bd/Main_block/Main_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block || ORIG_REF_NAME==Main_block} -quiet] -quiet

# IP: bd/Main_block/ip/Main_block_Speed_sensor_input_d_0_0/Main_block_Speed_sensor_input_d_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block_Speed_sensor_input_d_0_0 || ORIG_REF_NAME==Main_block_Speed_sensor_input_d_0_0} -quiet] -quiet

# Block Designs: bd/Speed_sensor_input_dec/Speed_sensor_input_dec.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec || ORIG_REF_NAME==Speed_sensor_input_dec} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_pulsecounter_0_0/Speed_sensor_input_dec_pulsecounter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_pulsecounter_0_0} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_ClockDivider1kHz_0_0/Speed_sensor_input_dec_ClockDivider1kHz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_ClockDivider1kHz_0_0} -quiet] -quiet

# IP: bd/Speed_sensor_input_dec/ip/Speed_sensor_input_dec_speedcalc_0_0/Speed_sensor_input_dec_speedcalc_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Speed_sensor_input_dec_speedcalc_0_0 || ORIG_REF_NAME==Speed_sensor_input_dec_speedcalc_0_0} -quiet] -quiet

# IP: bd/Main_block/ip/Main_block_PWM_Gen_Daan_wrapper_0_0/Main_block_PWM_Gen_Daan_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block_PWM_Gen_Daan_wrapper_0_0 || ORIG_REF_NAME==Main_block_PWM_Gen_Daan_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/PWM_Gen_Daan/PWM_Gen_Daan.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan || ORIG_REF_NAME==PWM_Gen_Daan} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmcalculator_0_0/PWM_Gen_Daan_pwmcalculator_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmcalculator_0_0} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_pwmsimple_0_0/PWM_Gen_Daan_pwmsimple_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_pwmsimple_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_pwmsimple_0_0} -quiet] -quiet

# IP: bd/PWM_Gen_Daan/ip/PWM_Gen_Daan_ClockDivider100kHz_0_0/PWM_Gen_Daan_ClockDivider100kHz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0 || ORIG_REF_NAME==PWM_Gen_Daan_ClockDivider100kHz_0_0} -quiet] -quiet

# IP: bd/Main_block/ip/Main_block_seg_display_Daan_wra_0_0/Main_block_seg_display_Daan_wra_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block_seg_display_Daan_wra_0_0 || ORIG_REF_NAME==Main_block_seg_display_Daan_wra_0_0} -quiet] -quiet

# Block Designs: bd/seg_display_Daan/seg_display_Daan.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan || ORIG_REF_NAME==seg_display_Daan} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_bin14_to_bcd_0_0/seg_display_Daan_bin14_to_bcd_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_bin14_to_bcd_0_0 || ORIG_REF_NAME==seg_display_Daan_bin14_to_bcd_0_0} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_ClockDivider4kHz_0_0/seg_display_Daan_ClockDivider4kHz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_ClockDivider4kHz_0_0 || ORIG_REF_NAME==seg_display_Daan_ClockDivider4kHz_0_0} -quiet] -quiet

# IP: bd/seg_display_Daan/ip/seg_display_Daan_SevenSegmentDriver_0_0/seg_display_Daan_SevenSegmentDriver_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==seg_display_Daan_SevenSegmentDriver_0_0 || ORIG_REF_NAME==seg_display_Daan_SevenSegmentDriver_0_0} -quiet] -quiet

# IP: bd/Main_block/ip/Main_block_xlconstant_0_0/Main_block_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block_xlconstant_0_0 || ORIG_REF_NAME==Main_block_xlconstant_0_0} -quiet] -quiet

# IP: bd/Main_block/ip/Main_block_clk_wiz_0_0/Main_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Main_block_clk_wiz_0_0 || ORIG_REF_NAME==Main_block_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/seg_display_Daan/seg_display_Daan_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Speed_sensor_input_dec/Speed_sensor_input_dec_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/PWM_Gen_Daan/PWM_Gen_Daan_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/seg_display_Daan/seg_display_Daan_ooc.xdc

# XDC: c:/Users/daanv/Documents/GitHub/MO5_MO6/MO5/Self_driving_car/Self_driving_car.gen/sources_1/bd/Main_block/Main_block_ooc.xdc
